pipelines:
  pipe1:
    group: defaultGroup
    materials:
      mygit:
        git: https://github.com/jeevansai502/entity-examples.git
    stages:
      - html:
          jobs:
            html:
              artifacts:
               - external:
                   id: "test-123"
                   store_id: "test-store"
                   configuration:
                      options:
                        Source: a.html
                        Destination: "${{GO_ARTIFACT_LOCATOR}}"
              tasks:
               - exec:
                   arguments:
                     - -c
                     - echo "<a href=https://www.google.com>mobile-app.apk</a>" > a.html
                   command: bash
