pipelines:
  pipe1:
    group: defaultGroup
    materials:
      mygit:
        git: https://github.com/jeevansai502/entity-examples.git
    stages:
      - html:
          jobs:
            html:
              artifacts:
               - build:
                   source: a.html
                   destination: ''
              tasks:
               - exec:
                   command: echo "<html>\n<body>\n\n\n<a href=https://www.google.com>mobile-app.apk</a>\n\n\n</body>\n</html>" > a.html
