pipelines:
  pipe1:
    group: defaultGroup
    materials:
      mygit:
        git: https://github.com/jeevansai502/entity-examples.git
    stages:
      - html:
          jobs:
            html:
              artifacts:
               - build:
                   source: a.html
                   destination: ''
              tasks:
               - exec:
                   arguments:
                     - -c
                     - echo "<a href=https://www.google.com>mobile-app.apk</a>" > a.html
                   command: bash
