pipelines:
  pipe1:
    group: defaultGroup
    materials:
      mygit:
        git: https://github.com/jeevansai502/entity-examples.git
    stages:
      - html:
          jobs:
            html:
              tabs:
                report: f1/f2/a.html
              artifacts:
               - build:
                   source: f1/f2/a.html
                   destination: ''
               - external:
                   id: "test-123"
                   store_id: "test-store"
                   configuration:
                      options:
                        Source: f1/f2/a.html
                        Destination: "${GO_ARTIFACT_LOCATOR}"
              tasks:
               - exec:
                   arguments:
                     - -c
                     - mkdir -p f1/f2 && echo "<a href=https://www.google.com>mobile-app.apk</a>" > f1/f2/a.html
                   command: bash
